# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c7f3795b0efb6005ce49ef426d88a5c1d35f41b40679319acda76caec992863ff2e48808074dc5851dfd9dd31fb36cdb1e202767242ed300013a3f69440bf3

test:
  secret_key_base: 82df8f31a79e037285888b303591293556603addd92662f93c50feaec5957a591810145f5c0fa6db442cd33d7bea953b4da2d0a132377b26367042914e450552

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
